/** Lista inicial — ISO 3166-1 alpha-2 (minúsculas) para flagcdn.com */
window.PAISES_QUIZ = [
  { code: "br", nome: "Brasil" },
  { code: "ar", nome: "Argentina" },
  { code: "fr", nome: "França" },
  { code: "co", nome: "Colômbia" },
  { code: "cu", nome: "Cuba" },
  { code: "ht", nome: "Haiti" },
  { code: "lr", nome: "Libéria" },
  { code: "pt", nome: "Portugal" },
  { code: "es", nome: "Espanha" },
  { code: "it", nome: "Itália" },
  { code: "de", nome: "Alemanha" },
  { code: "gb", nome: "Reino Unido" },
  { code: "us", nome: "Estados Unidos" },
  { code: "ca", nome: "Canadá" },
  { code: "mx", nome: "México" },
  { code: "jp", nome: "Japão" },
  { code: "cn", nome: "China" },
  { code: "in", nome: "Índia" },
  { code: "au", nome: "Austrália" },
  { code: "za", nome: "África do Sul" },
  { code: "eg", nome: "Egito" },
  { code: "ng", nome: "Nigéria" },
  { code: "ke", nome: "Quênia" },
  { code: "cl", nome: "Chile" },
  { code: "pe", nome: "Peru" },
  { code: "uy", nome: "Uruguai" },
  { code: "py", nome: "Paraguai" },
  { code: "bo", nome: "Bolívia" },
  { code: "ec", nome: "Equador" },
  { code: "ve", nome: "Venezuela" },
];
